"""add ai log tables

Revision ID: e2781da10f01
Revises: 
Create Date: 2026-03-06 01:45:46.190207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2781da10f01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_mulakat_request_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('transcript_length', sa.Integer(), nullable=True),
    sa.Column('prompt_length', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('total_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_mulakat_task_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_length', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_mulakat_task_log')
    op.drop_table('ai_mulakat_request_log')
    # ### end Alembic commands ###
